### ISSUE TITLE
Not shame value in SHA3

### ISSUE THREAD

**Issue by jposes22** [gabriel/NACrypto#1]
Hi i don´t know if a issue or not but ...
In your test proyect you put the following code to get a digest SHA3 512:
`
- (void)test {
  NSData *data = [@"abc" dataUsingEncoding:NSUTF8StringEncoding];
 
  NSData *SHA3_384 = [NASHA3 SHA3ForData:data digestBitLength:384];
  NSData *expected384 = [@"f7df1165f033337be098e7d288ad6a2f74409d7a60b49c36642218de161b1f99f8c681e4afaf31a34db29fb763e3c28e" na_dataFromHexString];
  XCTAssertEqualObjects(SHA3_384, expected384);
  
  NSData *SHA3 = [NASHA3 SHA3ForData:data digestBitLength:512];
  NSData *expected = [@"18587dc2ea106b9a1563e32b3312421ca164c7f1f07bc922a9c83d77cea3a1e5d0c69910739025372dc14ac9642629379540c17e2a65b19d77aa511a9d00bb96" na_dataFromHexString];
  XCTAssertEqualObjects(SHA3, expected);
}
`
And the hash of "abc" is in your case 18587dc2ea106b9a1563e32b3312421ca164c7f1f07bc922a9c83d77cea3a1e5d0c69910739025372dc14ac9642629379540c17e2a65b19d77aa511a9d00bb96

But if you use Bouncy Castle in Java I don´t get the same code than this library:
https://www.bouncycastle.org/
https://emn178.github.io/online-tools/sha3_512.html
https://www.browserling.com/tools/sha3-hash

I give with Java or other webs: b751850b1a57168a5693cd924b6b096e08f621827444f70d884f5d0240d2712e10e116e9192af3c91a7ec57647e3934057340b4cf408d5a56592f8274eec53f0

What is the problem? I want to use your library because it´s incredible but with different results I can´t use it ;( please help me what´s wrong?

**Comment by gabriel** [comment]
The SHA3 in this library is Keccak:
https://emn178.github.io/online-tools/keccak_512.html

**Comment by gabriel** [comment]
I'm not quite sure why sha3 and keccak are different (I thought they were the same), so am reading about that now.

**Comment by gabriel** [comment]
The standard wasn't finalized when I wrote this.

Just pushed a new version 1.1.0 with SHA3 and Keccak separated.
